### ISSUE TITLE
compilation error on Ubuntu 16.04

### ISSUE THREAD

**Issue by clement-analogue** [nicehash/nheqminer#308]
Edit: My mistake, for some reason, I had a file `list` in my home directory that messed up the compilation.

I have the following error when I try to compile on Ubuntu 16.04, gcc 5.4, Boost 1.64

```
% make            
[ 13%] Built target cuda_djezo
[ 22%] Built target cpu_xenoncat
[ 27%] Building CXX object CMakeFiles/nheqminer.dir/nheqminer/amount.cpp.o
In file included from /home/clement/nheqminer/nheqminer/serialize.h:19:0,
                 from /home/clement/nheqminer/nheqminer/amount.h:9,
                 from /home/clement/nheqminer/nheqminer/amount.cpp:6:
/home/clement/build/../list:2:1: error: expected constructor, destructor, or type conversion before ‘*’ token
 *bind
 ^
In file included from /usr/local/include/boost/throw_exception.hpp:42:0,
                 from /usr/local/include/boost/array.hpp:51,
                 from /home/clement/nheqminer/nheqminer/serialize.h:28,
                 from /home/clement/nheqminer/nheqminer/amount.h:9,
                 from /home/clement/nheqminer/nheqminer/amount.cpp:6:
/usr/local/include/boost/exception/exception.hpp:145:40: error: expected declaration before end of line
CMakeFiles/nheqminer.dir/build.make:62: recipe for target 'CMakeFiles/nheqminer.dir/nheqminer/amount.cpp.o' failed
make[2]: *** [CMakeFiles/nheqminer.dir/nheqminer/amount.cpp.o] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/nheqminer.dir/all' failed
make[1]: *** [CMakeFiles/nheqminer.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
