### ISSUE TITLE
Broken build on Linux branch

### ISSUE THREAD

**Issue by loxal** [nicehash/nheqminer#134]
I get the following building 3044e043f9fb1fca77b71f8f42916286cad63b32 on Linux branch

[ 27%] Building CXX object CMakeFiles/nheqminer_cpu.dir/home/alex/mine/nheqminer/nheqminer/json/json_spirit_reader.cpp.o
[ 33%] Building CXX object CMakeFiles/nheqminer_cpu.dir/home/alex/mine/nheqminer/nheqminer/json/json_spirit_value.cpp.o
[ 38%] Building CXX object CMakeFiles/nheqminer_cpu.dir/home/alex/mine/nheqminer/nheqminer/json/json_spirit_writer.cpp.o
[ 44%] Building CXX object CMakeFiles/nheqminer_cpu.dir/home/alex/mine/nheqminer/nheqminer/libstratum/ZcashStratum.cpp.o
In file included from /home/alex/mine/nheqminer/nheqminer/libstratum/ZcashStratum.h:19:0,
                 from /home/alex/mine/nheqminer/nheqminer/libstratum/ZcashStratum.cpp:6:
/home/alex/mine/nheqminer/Linux_cmake/nheqminer_cpu/../../nheqminer/SolverStub.h:8:45: warning: backslash-newline at end of file
 #define CREATE_SOLVER_STUB(NAME, STUB_NAME) \
                                             ^
[ 50%] Building CXX object CMakeFiles/nheqminer_cpu.dir/home/alex/mine/nheqminer/nheqminer/main.cpp.o
In file included from /home/alex/mine/nheqminer/Linux_cmake/nheqminer_cpu/../../nheqminer/libstratum/ZcashStratum.h:19:0,
                 from /home/alex/mine/nheqminer/nheqminer/libstratum/StratumClient.h:7,
                 from /home/alex/mine/nheqminer/nheqminer/main.cpp:8:
/home/alex/mine/nheqminer/Linux_cmake/nheqminer_cpu/../../nheqminer/SolverStub.h:8:45: warning: backslash-newline at end of file
 #define CREATE_SOLVER_STUB(NAME, STUB_NAME) \
                                             ^
In file included from /home/alex/mine/nheqminer/nheqminer/../ocl_device_utils/ocl_device_utils.h:6:0,
                 from /home/alex/mine/nheqminer/nheqminer/main.cpp:10:
/home/alex/mine/nheqminer/nheqminer/../ocl_device_utils/cl_ext.hpp:168:56: fatal error: CL/cl_ext.h: No such file or directory
compilation terminated.
CMakeFiles/nheqminer_cpu.dir/build.make:254: recipe for target 'CMakeFiles/nheqminer_cpu.dir/home/alex/mine/nheqminer/nheqminer/main.cpp.o' failed
make[2]: *** [CMakeFiles/nheqminer_cpu.dir/home/alex/mine/nheqminer/nheqminer/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/nheqminer_cpu.dir/all' failed
make[1]: *** [CMakeFiles/nheqminer_cpu.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by DavBE** [comment]
Same here, Ubuntu 15.10  : fatal error: CL/cl_ext.h: No such file or directory

Works on Ubuntu 16.04 though.

**Comment by loxal** [comment]
Works at least with fa1323da5ad00447cace5da9e64ab07d702bcc95

**Comment by NotOnlyCode** [comment]
Same here, Ubuntu 16.04
fatal error: CL/cl_ext.h: No such file or directory

**Comment by loxal** [comment]
Introduced in 2a937fe690739a296bd4d9cbab1dd34c4372088e

**Comment by loxal** [comment]
c899113a72cc8a11210cd555e3e10f39988fc2a6 works fine

**Comment by S74nk0** [comment]
Try the latest commit. This should fix the error.

**Comment by NotOnlyCode** [comment]
This time
fatal error: GL/gl.h: No such file or directory

**Comment by S74nk0** [comment]
did you install `sudo apt-get install mesa-common-dev`? On Ubuntu 16.04 this installs gl dev libs.

**Comment by PCFiL** [comment]
installed mesa-common-dev and now having :
nheqminer/nheqminer/../ocl_device_utils/cl_ext.hpp:177:23: fatal error: CL/opencl.h: No such file or directory
using 16.04

**Comment by S74nk0** [comment]
@PCFiL following [these](https://github.com/nicehash/nheqminer/tree/Linux#linux-1604-build-ocl_xmp-ocl_silentarmy) exact instructions there were build error?

**Comment by PCFiL** [comment]
@S74nk0 on this box i only want to CPU mine (no usable GPU in that box)
and using latest commit, i have those err. is there any flags to disable gpu mining atm?
thanks.

**Comment by DavBE** [comment]
@S74nk0 

I get the same error following these instructions : 
https://github.com/nicehash/nheqminer/tree/Linux#linux-ubuntu-1404--1604-build-cpu_xenoncat

**Comment by NotOnlyCode** [comment]
same here

**Comment by hsacz** [comment]
I get the same error - building 16.04 / Nvidia -  tromp and xenoncat -

**Comment by S74nk0** [comment]
I see. Working on the fixes very soon.

**Comment by S74nk0** [comment]
Ok I have pushed the fixes. CPU compiles don't have a CUDA Linux rig at hand. Al should compile now. Please confirm this for CUDA who can.

**Comment by juanjgit** [comment]
There are some watnings, but it works:
`[ 44%] Building CXX object CMakeFiles/nheqminer_cpu.dir/root/nheqminer/nheqminer/libstratum/ZcashStratum.cpp.o
[ 50%] Building CXX object CMakeFiles/nheqminer_cpu.dir/root/nheqminer/nheqminer/main.cpp.o
[ 55%] Building CXX object CMakeFiles/nheqminer_cpu.dir/root/nheqminer/nheqminer/primitives/block.cpp.o
In file included from /root/nheqminer/nheqminer/libstratum/ZcashStratum.h:19:0,
                 from /root/nheqminer/nheqminer/libstratum/ZcashStratum.cpp:6:
/root/nheqminer/Linux_cmake/nheqminer_cpu/../../nheqminer/SolverStub.h:8:45: warning: backslash-newline at end of file
 #define CREATE_SOLVER_STUB(NAME, STUB_NAME) \
                                             ^
[ 61%] Building CXX object CMakeFiles/nheqminer_cpu.dir/root/nheqminer/nheqminer/speed.cpp.o
[ 66%] Building CXX object CMakeFiles/nheqminer_cpu.dir/root/nheqminer/nheqminer/uint256.cpp.o
In file included from /root/nheqminer/Linux_cmake/nheqminer_cpu/../../nheqminer/libstratum/ZcashStratum.h:19:0,
                 from /root/nheqminer/nheqminer/libstratum/StratumClient.h:7,
                 from /root/nheqminer/nheqminer/main.cpp:8:
/root/nheqminer/Linux_cmake/nheqminer_cpu/../../nheqminer/SolverStub.h:8:45: warning: backslash-newline at end of file
 #define CREATE_SOLVER_STUB(NAME, STUB_NAME) \
                                             ^
[ 72%] Building CXX object CMakeFiles/nheqminer_cpu.dir/root/nheqminer/nheqminer/utilstrencodings.cpp.o
[ 77%] Building CXX object CMakeFiles/nheqminer_cpu.dir/root/nheqminer/nheqminer/libstratum/StratumClient.cpp.o
[ 83%] Building CXX object CMakeFiles/nheqminer_cpu.dir/root/nheqminer/cpu_tromp/blake2/blake2bx.cpp.o
[ 88%] Building CXX object CMakeFiles/nheqminer_cpu.dir/root/nheqminer/cpu_tromp/cpu_tromp.cpp.o
In file included from /root/nheqminer/Linux_cmake/nheqminer_cpu/../../nheqminer/libstratum/ZcashStratum.h:19:0,
                 from /root/nheqminer/nheqminer/libstratum/StratumClient.h:7,
                 from /root/nheqminer/nheqminer/libstratum/StratumClient.cpp:6:
/root/nheqminer/Linux_cmake/nheqminer_cpu/../../nheqminer/SolverStub.h:8:45: warning: backslash-newline at end of file
 #define CREATE_SOLVER_STUB(NAME, STUB_NAME) \
                                             ^
[ 94%] Building CXX object CMakeFiles/nheqminer_cpu.dir/root/nheqminer/cpu_xenoncat/xenoncat.cpp.o


[100%] Linking CXX executable nheqminer_cpu
[100%] Built target nheqminer_cpu
`

**Comment by S74nk0** [comment]
The scattered cmake files will be merged into a single cmake... we will make code cleanups and audits.

**Comment by hsacz** [comment]
CPU xenoncat compiles ok (with a couple of warnings) warning: backslash-newline at end of file
 #define CREATE_SOLVER_STUB(NAME, STUB_NAME) \

CUDA doesn't compile main.cpp:  (.text+0x56f): undefined reference to `cuda_tromp::getcount()'
main.cpp:(.text+0x668): undefined reference to `cuda_tromp::getinfo(int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, int&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
collect2: error: ld returned 1 exit status

**Comment by loxal** [comment]
Yes, works now, with a bunch of compilation warnings.

**Comment by loxal** [comment]
Now, I get 

[ 33%] Building CXX object CMakeFiles/nheqminer_cpu.dir/home/alex/mine/nheqminer/nheqminer/json/json_spirit_value.cpp.o
[ 38%] Building CXX object CMakeFiles/nheqminer_cpu.dir/home/alex/mine/nheqminer/nheqminer/json/json_spirit_writer.cpp.o
[ 44%] Building CXX object CMakeFiles/nheqminer_cpu.dir/home/alex/mine/nheqminer/nheqminer/libstratum/ZcashStratum.cpp.o
In file included from /home/alex/mine/nheqminer/nheqminer/libstratum/ZcashStratum.h:19:0,
                 from /home/alex/mine/nheqminer/nheqminer/libstratum/ZcashStratum.cpp:6:
/home/alex/mine/nheqminer/Linux_cmake/nheqminer_cpu/../../nheqminer/SolverStub.h:8:45: warning: backslash-newline at end of file
 #define CREATE_SOLVER_STUB(NAME, STUB_NAME) \
                                             ^
[ 50%] Building CXX object CMakeFiles/nheqminer_cpu.dir/home/alex/mine/nheqminer/nheqminer/main.cpp.o
In file included from /home/alex/mine/nheqminer/Linux_cmake/nheqminer_cpu/../../nheqminer/libstratum/ZcashStratum.h:19:0,
                 from /home/alex/mine/nheqminer/nheqminer/libstratum/StratumClient.h:7,
                 from /home/alex/mine/nheqminer/nheqminer/main.cpp:8:
/home/alex/mine/nheqminer/Linux_cmake/nheqminer_cpu/../../nheqminer/SolverStub.h:8:45: warning: backslash-newline at end of file
 #define CREATE_SOLVER_STUB(NAME, STUB_NAME) \
                                             ^
In file included from /home/alex/mine/nheqminer/nheqminer/../ocl_device_utils/ocl_device_utils.h:6:0,
                 from /home/alex/mine/nheqminer/nheqminer/main.cpp:10:
/home/alex/mine/nheqminer/nheqminer/../ocl_device_utils/cl_ext.hpp:168:56: fatal error: CL/cl_ext.h: No such file or directory
compilation terminated.
CMakeFiles/nheqminer_cpu.dir/build.make:254: recipe for target 'CMakeFiles/nheqminer_cpu.dir/home/alex/mine/nheqminer/nheqminer/main.cpp.o' failed
make[2]: *** [CMakeFiles/nheqminer_cpu.dir/home/alex/mine/nheqminer/nheqminer/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/nheqminer_cpu.dir/all' failed
make[1]: *** [CMakeFiles/nheqminer_cpu.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
./mine_zcash.sh: line 15: ./nheqminer_cpu: No such file or directory

**Comment by S74nk0** [comment]
@loxal try cleaning the CMake cache and generated files. CUDA is still broken (working on it) others should work.

**Comment by loxal** [comment]
Thanks, now it worked with a bunch of compilation warnings:

> [ 44%] Building CXX object CMakeFiles/nheqminer_cpu.dir/home/alex/mine/nheqminer/nheqminer/libstratum/ZcashStratum.cpp.o
In file included from /home/alex/mine/nheqminer/nheqminer/libstratum/ZcashStratum.h:19:0,
                 from /home/alex/mine/nheqminer/nheqminer/libstratum/ZcashStratum.cpp:6:
/home/alex/mine/nheqminer/Linux_cmake/nheqminer_cpu/../../nheqminer/SolverStub.h:8:45: warning: backslash-newline at end of file
 #define CREATE_SOLVER_STUB(NAME, STUB_NAME) \
                                             ^
[ 50%] Building CXX object CMakeFiles/nheqminer_cpu.dir/home/alex/mine/nheqminer/nheqminer/main.cpp.o
In file included from /home/alex/mine/nheqminer/Linux_cmake/nheqminer_cpu/../../nheqminer/libstratum/ZcashStratum.h:19:0,
                 from /home/alex/mine/nheqminer/nheqminer/libstratum/StratumClient.h:7,
                 from /home/alex/mine/nheqminer/nheqminer/main.cpp:8:
/home/alex/mine/nheqminer/Linux_cmake/nheqminer_cpu/../../nheqminer/SolverStub.h:8:45: warning: backslash-newline at end of file
 #define CREATE_SOLVER_STUB(NAME, STUB_NAME) \
                                             ^
[ 55%] Building CXX object CMakeFiles/nheqminer_cpu.dir/home/alex/mine/nheqminer/nheqminer/primitives/block.cpp.o
[ 61%] Building CXX object CMakeFiles/nheqminer_cpu.dir/home/alex/mine/nheqminer/nheqminer/speed.cpp.o
[ 66%] Building CXX object CMakeFiles/nheqminer_cpu.dir/home/alex/mine/nheqminer/nheqminer/uint256.cpp.o
[ 72%] Building CXX object CMakeFiles/nheqminer_cpu.dir/home/alex/mine/nheqminer/nheqminer/utilstrencodings.cpp.o
[ 77%] Building CXX object CMakeFiles/nheqminer_cpu.dir/home/alex/mine/nheqminer/nheqminer/libstratum/StratumClient.cpp.o
In file included from /home/alex/mine/nheqminer/Linux_cmake/nheqminer_cpu/../../nheqminer/libstratum/ZcashStratum.h:19:0,
                 from /home/alex/mine/nheqminer/nheqminer/libstratum/StratumClient.h:7,
                 from /home/alex/mine/nheqminer/nheqminer/libstratum/StratumClient.cpp:6:
/home/alex/mine/nheqminer/Linux_cmake/nheqminer_cpu/../../nheqminer/SolverStub.h:8:45: warning: backslash-newline at end of file
 #define CREATE_SOLVER_STUB(NAME, STUB_NAME) \
                                             ^
[ 83%] Building CXX object CMakeFiles/nheqminer_cpu.dir/home/alex/mine/nheqminer/cpu_tromp/blake2/blake2bx.cpp.o
[ 88%] Building CXX object CMakeFiles/nheqminer_cpu.dir/home/alex/mine/nheqminer/cpu_tromp/cpu_tromp.cpp.o
[ 94%] Building CXX object CMakeFiles/nheqminer_cpu.dir/home/alex/mine/nheqminer/cpu_xenoncat/xenoncat.cpp.o
[100%] Linking CXX executable nheqminer_cpu

**Comment by S74nk0** [comment]
Latest commits fix CUDA build as well. Closing issue.
